package br.com.fiap.cheffy.shared.exception.keys;

public enum ExceptionsKeys {
    //General Error Messages
    GENERIC_RESOURCE_NOT_FOUND,
    PROPERTY_BINDING_ERROR,
    INVALID_FORMAT_ERROR,
    ERROR_ON_DESERIALIZATION,
    GENERIC_ERROR_MESSAGE,
    ARGUMENT_NOT_VALID_ERROR,
    INVALID_OPERATION_EXCEPTION,

    //Profile
    PROFILE_NOT_FOUND_EXCEPTION,
    PROFILE_ALREADY_EXIST_EXCEPTION,


    //Adress
    ADDRESS_NOT_FOUND_EXCEPTION,

    //User
    USER_NOT_FOUND_EXCEPTION,
    REGISTER_FAILED_EXCEPTION,
    USER_MUST_HAVE_AT_LEAST_ONE_ADDRESS,

    //Login
    LOGIN_FAILED_EXCEPTION,

    //Auth
    TOKEN_EXPIRED_EXCEPTION,
    INVALID_PASSWORD_MSG,
    INVALID_POSTAL_CODE_MSG,

    //RESTAURANT
    RESTAURANT_INVALID_WORKING_TIME,
    WORKING_TIME_TOO_SHORT,
}